/** Every element the page script touches, looked up once. */

const $ = (id) => document.getElementById(id);

export const els = {
  title: $("title"), subtitle: $("subtitle"), languageLabel: $("language-label"),
  themeLabel: $("theme-label"),
  text: $("text"), textLabel: $("text-label"), speak: $("speak"), cancel: $("cancel"),
  status: $("status"),
  examplesLabel: $("examples-label"), examples: $("examples"),
  audio: $("audio"), audioLabel: $("audio-label"), download: $("download"), stats: $("stats"),
  parameters: $("parameters-heading"),
  speed: $("speed"), speedValue: $("speed-value"), speedLabel: $("speed-label"), speedInfo: $("speed-info"),
  variation: $("variation"), variationValue: $("variation-value"),
  variationLabel: $("variation-label"), variationInfo: $("variation-info"),
  seed: $("seed"), seedLabel: $("seed-label"), seedInfo: $("seed-info"), shuffle: $("shuffle"),
  normalise: $("normalise"), normaliseLabel: $("normalise-label"), normaliseInfo: $("normalise-info"),
  advancedLabel: $("advanced-label"),
  maxWords: $("max-words"), maxWordsValue: $("max-words-value"),
  maxWordsLabel: $("max-words-label"), maxWordsInfo: $("max-words-info"),
  chunks: $("chunks"), chunksLabel: $("chunks-label"), chunksInfo: $("chunks-info"),
  voiceLabel: $("voice-label"), voiceInfo: $("voice-info"),
  offlineNote: $("offline-note"), speedNote: $("speed-note"),
  footer: $("footer"), censorNote: $("censor-note"), aboutLabel: $("about-label"),
  feedbackLink: $("feedback-link"),
  skipLink: document.querySelector(".skip-link"),
  wave: $("wave"), waveBox: document.querySelector(".wave"), waveEmpty: $("wave-empty"),
  progress: $("progress"), elapsed: $("elapsed"), slowNote: $("slow-note"),
  phoneNote: $("phone-note"), phoneNoteText: $("phone-note-text"), phoneWhy: $("phone-why"),
  result: $("result"), resultReady: $("result-ready"), resultReadyText: $("result-ready-text"),
  modeBanner: $("mode-banner"), modeTitle: $("mode-title"), modeText: $("mode-text"),
  modeGpu: $("mode-gpu"), modeAction: $("mode-action"), modeBadge: $("mode-badge"),
  copyDiagnostics: $("copy-diagnostics"), copyStatus: $("copy-status"), diagnostics: $("diagnostics"),
  deviceCard: $("device-card"), deviceMeter: document.querySelector("#device-card .meter"),
  deviceLabel: $("device-label"), deviceTitle: $("device-title"), deviceDetails: $("device-details"),
  dialog: $("device-dialog"), dialogMeter: document.querySelector("#device-dialog .meter"),
  dialogTitle: $("dialog-title"), dialogText: $("dialog-text"), dialogNote: $("dialog-note"),
  dialogDontShow: $("dialog-dont-show"), dialogDontShowLabel: $("dialog-dont-show-label"),
  dialogDirect: $("dialog-direct"), dialogOk: $("dialog-ok"),
  dialogMain: $("dialog-main"), dialogTech: $("dialog-tech"), dialogTechList: $("dialog-tech-list"),
  dialogTechOpen: $("dialog-tech-open"), dialogTechBack: $("dialog-tech-back"),
  toasts: $("toasts"), textError: $("text-error"), textCount: $("text-count"),
  textWarning: $("text-warning"),
};
