/**
 * Port of `aztts/az_profanity.py`: obscenities become a bleep.
 *
 * The playground always censors, in both voices -- there is no option to turn
 * it off here. Speaking obscenities is only possible from a clone, with
 * `say.py --allow-profanity`. `web/tests/test_az_censor.mjs` checks this file
 * against output generated by the Python module.
 */

import { azLower } from "./az-text.js";

export const BLEEP = "█";

// Language data -- keep identical to PROFANE_STEMS in az_profanity.py.
const PROFANE_STEMS = [
  "sik", "qəhbə", "gəhbə", "amcı", "götverən", "götbaş", "yarraq", "yarrağ",
  "qancıq", "qancığ", "orospu", "oruspu", "peysər", "pezəvəng", "pezevenk",
  "dəyyus", "dəyus", "yavşaq", "yavsaq", "yavşağ", "gicdıllaq", "gijdıllaq",
  "sürtük", "itoğlu", "köpəkoğlu", "köpəyoğlu",
  "blyat", "blyad", "bılyat", "dalbayob", "dolbayob", "dalbayeb", "dolbaeb",
  "pidar", "pidor", "pizd", "yeba", "mudak", "mudaq", "mudil",
  "бля", "пизд", "хуй", "хуе", "хуё", "ебат", "ебан", "ёбан", "мудак",
  "пидор", "пидар",
];

// Keep identical to CLEAN_PREFIXES.
const CLEAN_PREFIXES = [
  "sikk", "sikl", "sikh", "sikay", "sikest", "sikar", "sikan", "sikor",
];

// Keep identical to PROFANE_WORDS. Matched unfolded.
const PROFANE_WORDS = [
  "göt", "götü", "götün", "götünü", "götünə", "götündə", "götündən",
  "götə", "götdə", "götdən", "götlər", "götləri", "götlük",
  "gotu", "gotun", "gotunu", "gotune", "gotunde", "gotunden",
  "gotde", "gotden", "gotler", "gotleri", "gotluk",
  "amına", "amını", "amk",
  "piç", "piçi", "piçin", "piçlər",
  "suka", "sukalar", "naxuy", "nahuy", "xuy",
  "сука", "суки",
];

const FOLD = new Map(Object.entries({
  "ə": "e", "ı": "i", "ö": "o", "ü": "u", "ç": "c", "ğ": "g",
  "0": "o", "1": "i", "3": "e", "4": "a", "@": "a", "$": "s",
}));

// Python's `\w` is Unicode-aware and excludes combining marks; JavaScript's
// `\w` is ASCII-only, hence the explicit classes.
const TOKEN_RE = /[\p{L}\p{N}_@$]+(?:['’-][\p{L}\p{N}_@$]+)*/gu;
const PART_RE = /['’-]/u;
const HELD_RE = /(.)\1{2,}/gu;
const AMOUNT_RE = /^[$@]?\p{Nd}+(?:[.,]\p{Nd}+)*\p{L}{0,2}$/u;
const RUN_RE = new RegExp(`${BLEEP}(?:[\\s,;:\\-]+${BLEEP})+`, "gu");
const LEADING_MARKS_RE = /^[\s,.;:!?-]+/u;
const SPEAKABLE_RE = /[\p{L}\p{N}_]/u;
const FORMAT_RE = /\p{Cf}/gu;

function visible(text) {
  return text.normalize("NFC").replace(FORMAT_RE, "");
}

function plain(word) {
  return azLower(word).replace(HELD_RE, "$1");
}

function skeleton(word) {
  return plain(Array.from(azLower(word), (character) => FOLD.get(character) ?? character).join(""));
}

const STEMS = PROFANE_STEMS.map(skeleton);
const CLEAN = CLEAN_PREFIXES.map(skeleton);
const WORDS = new Set(PROFANE_WORDS.map(plain));

/** Whether one word, or any part of a hyphenated word, is obscene. */
export function isProfane(word) {
  return visible(word).split(PART_RE).some((part) => {
    if (!part || AMOUNT_RE.test(part)) return false;
    if (WORDS.has(plain(part))) return true;
    const form = skeleton(part);
    return STEMS.some((stem) => form.startsWith(stem))
      && !CLEAN.some((prefix) => form.startsWith(prefix));
  });
}

/** The text with each obscene word replaced by BLEEP; neighbours merge. */
export function censorAz(text) {
  const marked = visible(text).replace(TOKEN_RE, (token) => (isProfane(token) ? BLEEP : token));
  return marked.replace(RUN_RE, BLEEP);
}

/** A chunk cut into the pieces to speak and the BLEEPs between them. */
export function bleepSegments(chunk) {
  const segments = [];
  chunk.split(BLEEP).forEach((piece, index) => {
    if (index) segments.push(BLEEP);
    const spoken = piece.replace(LEADING_MARKS_RE, "").trim();
    if (SPEAKABLE_RE.test(spoken)) segments.push(spoken);
  });
  return segments;
}
